# Chapter 4. 데이터 표현과 특성 공학
- 데이터가 어떤 형태의 특성으로 구성되어 있는가보다 **데이터를 어떻게 표현하는가가 머신러닝 모델의 성능에 주는 영향이 큼**
- 특정 어플리케이션에 가장 적합한 데이터 표현을 찾는 것을 **특성 공학(feature engineering)이라 함**
- **올바른 데이터 표현은 지도 학습 모델에서 적절한 매개변수를 선택하는 것보다 성능에 더 큰 영향을 줌**

In [1]:
import sys
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import scipy as sp
import IPython
import sklearn
import mglearn

print('Python 버전:', sys.version)
print('numpy 버전:', np.__version__)
print('pandas 버전:', pd.__version__)
print('matplotlib 버전:', matplotlib.__version__)

print('SciFy 버전:', sp.__version__)
print('IPython 버전:', IPython.__version__)
print('scikit-learn 버전:', sklearn.__version__)

from sklearn.model_selection import train_test_split
#plt.rc('font', family="Apple SD Gothic Neo")

Python 버전: 3.9.12 (main, Apr  5 2022, 06:56:58)
[GCC 7.5.0]
numpy 버전: 1.21.5
pandas 버전: 1.4.2
matplotlib 버전: 3.5.1
SciFy 버전: 1.7.3
IPython 버전: 8.2.0
scikit-learn 버전: 1.0.2

## 4.1 범주형 변수
- 1994년 인구 조사 데이터베이스에서 추출한 미국 성인의 소득 데이터셋 사용

In [15]:
# 데이터 로딩, 해당 파일은 열 이름을 나타내는 헤더가 없으므로 header=None으로 지정하고
# 'names' 매개변수로 열 이름을 제공함
data = pd.read_csv(
    os.path.join(mglearn.datasets.DATA_PATH, 'adult.data'),
    header=None, index_col=False,
    names=['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race',
           'gender','capital-gain','capital-loss','hours-per-week','native-country','income'])

In [16]:
# 예제를 위해 몇개의 열만 선택
data = data[['age','workclass','education','gender','hours-per-week','occupation','income']]
data.head()

,age,workclass,education,gender,hours-per-week,occupation,income
0,39,State-gov,Bachelors,Male,40,Adm-clerical,<=50K
1,50,Self-emp-not-inc,Bachelors,Male,13,Exec-managerial,<=50K
2,38,Private,HS-grad,Male,40,Handlers-cleaners,<=50K
3,53,Private,11th,Male,40,Handlers-cleaners,<=50K
4,28,Private,Bachelors,Female,40,Prof-specialty,<=50K

### 4.1.1 원-핫-인코딩(가변수)
- 가변수는 범주형 변수를 0 또는 1 값을 가진 하나 이상의 새로운 특성으로 바꾼 것
- 원-핫 인코딩은 통계학에서 사용하는 더미 코딩과 비슷하지만 완전히 같지는 않음
> - 통계학에서는 k개의 값을 가진 범주형 특성을 k-1개의 특성으로 변환하는 것이 일반적
> - 통계학에서는 마지막 범주는 모든 열이 0으로 표현 -> 행렬의 랭크 부족 현상을 피하기 위함
> - 랭크 부족: 한 열이 다른 열에 의존적이거나 열의 값이 모두 0인 경우에 행렬 분해 방식에 따라 문제 발생 가능성 있음
- **훈련 세트와 테스트 세트에 범주형 값이 같은 방식으로 표현되어야 함**
> - 훈련 데이터와 테스트 데이터 포인트를 모두 포함하는 DataFrame을 사용해 get_dummies 함수를 호출하거나,
> - 각각 get_dummies를 호출한 후에 훈련 세트와 테스트 세트의 열 이름을 비교해 같은 속성인지를 확인해야함

#### <U>*문자열로 된 범주형 데이터 확인하기*</U>
- 입력 데이터의 유일값 등을 확인하는 작업이 필요함
- **pandas에서는 get_dummies 함수를 사용해 데이터를 매우 쉽게 인코딩 할 수 있음**

In [17]:
data.gender.value_counts()
# 실제 문제에서는 모든 범주형 특성들에 대해서 확인이 필요함

 Male      21790
 Female    10771
Name: gender, dtype: int64

In [18]:
print('원본 특성:\n', list(data.columns), '\n')
data_dummies = pd.get_dummies(data)
print('get_dummies 후의 특성:\n', list(data_dummies.columns))

원본 특성:
 ['age', 'workclass', 'education', 'gender', 'hours-per-week', 'occupation', 'income']

get_dummies 후의 특성:
 ['age', 'hours-per-week', 'workclass_ ?', 'workclass_ Federal-gov', 'workclass_ Local-gov', 'workclass_ Never-worked', 'workclass_ Private', 'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc', 'workclass_ State-gov', 'workclass_ Without-pay', 'education_ 10th', 'education_ 11th', 'education_ 12th', 'education_ 1st-4th', 'education_ 5th-6th', 'education_ 7th-8th', 'education_ 9th', 'education_ Assoc-acdm', 'education_ Assoc-voc', 'education_ Bachelors', 'education_ Doctorate', 'education_ HS-grad', 'education_ Masters', 'education_ Preschool', 'education_ Prof-school', 'education_ Some-college', 'gender_ Female', 'gender_ Male', 'occupation_ ?', 'occupation_ Adm-clerical', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct', 'occupation_ Other-service', 'occupation_ Priv-house-serv', 'occupation_ Prof-specialty', 'occupation_ Protective-serv', 'occupation_ Sales', 'occupation_ Tech-support', 'occupation_ Transport-moving', 'income_ <=50K', 'income_ >50K']

In [19]:
data_dummies.head()

,age,hours-per-week,workclass_ ?,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Never-worked,workclass_ Private,workclass_ Self-emp-inc,workclass_ Self-emp-not-inc,workclass_ State-gov,...,occupation_ Machine-op-inspct,occupation_ Other-service,occupation_ Priv-house-serv,occupation_ Prof-specialty,occupation_ Protective-serv,occupation_ Sales,occupation_ Tech-support,occupation_ Transport-moving,income_ <=50K,income_ >50K
0,39,40,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
1,50,13,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
2,38,40,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,53,40,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,28,40,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0

> - data_dummies의 values 속성을 이용해 DataFrame을 Numpy 배열로 바꿀수 있음
> - 특성과 타깃값을 분리하지 않는 실수 주의!

In [20]:
features = data_dummies.loc[:, 'age':'occupation_ Transport-moving']
# NumPy 배열 추출
X = features.values
y = data_dummies['income_ >50K'].values
print(X.shape)
print(y.shape)

(32561, 44)
(32561,)

In [21]:
# 훈련 및 점수 도출
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

print('테스트 점수: {:.2f}'.format(lr.score(X_test, y_test)))

테스트 점수: 0.81

/opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

### 4.1.2 숫자로 표현된 범주형 특성
- 변수내 형식이 숫자라고 하더라도 **인코딩된 값 사이에 어떤 순서도 없으면, 이 특성은 연속이 아닌 이산적이라고 생각해야 함**
- pandas의 get_dummies 함수는 숫자 특성은 모두 연속형이라고 생각해서 가변수를 만들지 않음

In [22]:
# 숫자 특성과 범주형 문자열 특성을 가진 DataFrame을 생성
demo_df = pd.DataFrame({'숫자 특성': [0,1,2,1],
                        '범주형 특성' : ['양말','여우','양말','상자']})
demo_df

   숫자 특성 범주형 특성
0      0     양말
1      1     여우
2      2     양말
3      1     상자

In [23]:
# get_dummies를 사용하면 문자열 특성만 인코딩되며 숫자 특성은 바뀌지 않음
pd.get_dummies(demo_df)

   숫자 특성  범주형 특성_상자  범주형 특성_양말  범주형 특성_여우
0      0          0          1          0
1      1          0          0          1
2      2          0          1          0
3      1          1          0          0

> - 숫자 특성'도 가변수로 만들고 싶다면 ***columns* 매개변수**에 인코딩하고 싶은 열을 명시해야함
> - **columns 매개변수를 지정하지 않더라도 숫자를 문자열로 바꾸면 가변수 특성 생성 가능**, 아래 예시는 2개다 사용한 것으로 실무에서는 한 방법만 사용

In [24]:
pd.get_dummies(demo_df, columns=['숫자 특성', '범주형 특성'])

   숫자 특성_0  숫자 특성_1  숫자 특성_2  범주형 특성_상자  범주형 특성_양말  범주형 특성_여우
0        1        0        0          0          1          0
1        0        1        0          0          0          1
2        0        0        1          0          1          0
3        0        1        0          1          0          0

## 4.2-4.3 OneHotEncoder와 ColumnTransformer: scikit-learn으로 범주형 변수 다루기
- 원-핫-인코딩은 OneHotEncoder 클래스에 구현
- **매개변수**
> - ***min_frequency*** : 특정 횟수 또는 비율보다 적게 등장하는 범주를 하나의 특성을 합칠 수 있음
> - ***max_categories*** : 원-핫 인코딩으로 만들어지는 특성의 개수를 제한 가능

In [25]:
from sklearn.preprocessing import OneHotEncoder

# sparse=False로 설정하면 OneHotEncoder가 희소 행렬이 아니라 넘파이 배열을 반환
ohe = OneHotEncoder(sparse=False)
print(ohe.fit_transform(demo_df))

[[1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]]

> - **scikit-learn의 출력은 DataFrame이 아니기 때문에 열이름이 없음**
> - 원본 범주형 변수 이름을 얻으려면 ***get_feature_names_out*** 메서드를 사용

In [26]:
ohe.get_feature_names_out()

array(['숫자 특성_0', '숫자 특성_1', '숫자 특성_2', '범주형 특성_상자', '범주형 특성_양말',
       '범주형 특성_여우'], dtype=object)

> - OneHotEncoder는 모든 특성을 범주형이라고 가정하기 때문에 **열마다 다른 변환을 적용하기 위해 CoulumnsTransformer 클래스를 사용**

In [27]:
data.head()

,age,workclass,education,gender,hours-per-week,occupation,income
0,39,State-gov,Bachelors,Male,40,Adm-clerical,<=50K
1,50,Self-emp-not-inc,Bachelors,Male,13,Exec-managerial,<=50K
2,38,Private,HS-grad,Male,40,Handlers-cleaners,<=50K
3,53,Private,11th,Male,40,Handlers-cleaners,<=50K
4,28,Private,Bachelors,Female,40,Prof-specialty,<=50K

#### <U>*전처리 캡슐화 관점*</U>

> - **각 열의 변환은 이름(ex.'scaling'), 변환기 객체(ex.StandardScaler()), 이 변환이 적용된 열 지정(열이름이나 정수 인덱스, 불리언 마스크로 선택)**
> - ColumnTransformer 안의 단계에 접근하려면 ***named_transformers_*** 속성을 사용 (이름 사용)
> - **ColumnTransformer의 단점은 변환된 출력 열에 대응하는 입력 열을 찾지 못한다는 점(numpy 배열이므로 열 이름 없음)**

In [76]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

ct = ColumnTransformer(
    [('scaling', StandardScaler(), ['age','hours-per-week']),
     ('onehot', OneHotEncoder(sparse=False), ['workclass','education','gender','occupation'])])

> - train_test_split 함수에 넘파이 배열 대신에 특성을 포함하고 있는 DataFrame을 전달할 수 있음
> - 이렇게 하면 위 ColumnTransformer에 필요한 열이름을 보존하여 Transformer에 넘길 수 있음

In [77]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# income을 제외한 모든 열을 특성으로 추출
data_features = data.drop('income', axis=1)

# 데이터프레임과 income을 분할
X_train, X_test, y_train, y_test = train_test_split(data_features, data.income, random_state=0)

ct.fit(X_train)
X_train_trans = ct.transform(X_train)

print(X_train_trans.shape)

(24420, 44)

In [78]:
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train_trans, y_train)

X_test_trans = ct.transform(X_test)
print('테스트 점수: {:.2f}'.format(logreg.score(X_test_trans, y_test)))

테스트 점수: 0.81

In [79]:
print(ct.named_transformers_.onehot)
print(ct.named_transformers_.scaling)

OneHotEncoder(sparse=False)
StandardScaler()

> - ColumnTransformer를 만들면 각 단계 이름을 일일이 지정하는 것이 번거로움
> - 클래스 이름을 기반으로 자동으로 각 단계에 이름을 붙여주는 ***make_column_transformer*** 활용 가능

In [80]:
from sklearn.compose import make_column_transformer

ct = make_column_transformer(
    (StandardScaler(), ['age','hours-per-week']),
    (OneHotEncoder(sparse=False), ['workclass','education','gender','occupation']))

In [81]:
ct.fit(X_train)
X_train_trans = ct.transform(X_train)

In [88]:
print(ct.named_transformers_.onehotencoder)
print(ct.named_transformers_.standardscaler)

OneHotEncoder(sparse=False)
StandardScaler()